# Azure Client ID for managed identity
azureClientId: ""

# Service account name
serviceAccountName: demo-sa

# Namespace
namespace: demo

# App Registration (Service Principal) workload identity
workload:
  azureClientId: ""
  serviceAccountName: workload-sa
