apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-workload
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-workload
  template:
    metadata:
      labels:
        app: curl-workload
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.workload.serviceAccountName }}
      containers:
        - name: curl
          image: curlimages/curl:latest
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: AZURE_CLIENT_ID
              value: {{ .Values.workload.azureClientId | quote }}
