apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workload.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workload.azureClientId }}
  labels:
    azure.workload.identity/use: "true"
